### ISSUE TITLE
요구사항 중 선택한 게시글의 정보를 조회하는 기능이 누락됐습니다.

### ISSUE THREAD

**Issue by alaneelee** [BYEONGRYEOL/spring_lv1_sbl#1]
게시글의 id로 조회하는 API를 생성하면 좋을 것 같네요!

**Comment by BYEONGRYEOL** [comment]
놓쳤었는데, 감사합니다. 반영했습니다.
[read by id 기능 추가](https://github.com/BYEONGRYEOL/spring_lv1_sbl/commit/d5a6f583d45971dc8e868d82933bac399a601ff6)
