### ISSUE TITLE
DTO 중 PostDeleteRequest DTO가 사용되는 곳이 없습니다.

### ISSUE THREAD

**Issue by alaneelee** [BYEONGRYEOL/spring_lv1_sbl#2]
```java
public Long delete(
            @PathVariable
            @Schema(description = "게시글 id")
            Long id,
            @RequestHeader String password
    ) {
        return postService.delete(id, password);
}
```
컨트롤러에서 삭제 요청 시 비밀번호를 RequestHeader로 보내셨는데
PostDeleteRequest DTO를 사용하지 않고 header로 전달하신 이유가 궁금합니다.
보안상의 문제는 없을까요?

**Comment by BYEONGRYEOL** [comment]
초기에는 DELETE 요청에 POST 요청과 동일한 DTO를 사용했는데  password 이외의 불필요한 요청 body 데이터가 넘어가는 것 같아서 비밀번호만 담아서 요청할 수 있는 새로운 PostDeleteRequestDto 클래스를 작성해서 사용하다가, 어차피 password 한 개의 변수만 받을 것이라면
RequestHeader 에 String 형식으로 받아올 수 있지 않을까 생각했습니다.
[PostDeleteRequestDto 삭제한 commit log](https://github.com/BYEONGRYEOL/spring_lv1_sbl/commit/4adf3d1d716511f550fedff8dd1ab5884fd5ab84)

현재 사용하지않는 PostDeleteDto 클래스는 삭제하였고, 보안상의 문제는 검토해보겠습니다.

**Comment by BYEONGRYEOL** [comment]
기술 매니저님 말씀:
1. 어차피 클라이언트 단에서 암호화해서 넘어왔어야하긴하다.
2. RequestHeader보단 RequestBody로 받는게 보안상 더 유리한것이 맞다.
